---
version: "2.3"
services:
  video-consumer:
    image: kannie/video-consumer
    container_name: video-consumer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=unix$DISPLAY
      - KAFKA_TOPIC=meta_test
      - KAFKA_BOOTSTRAP_SERVERS=$DOCKER_HOST_IP:9092
      - KAFKA_CLIENT_ID="consumer1"
    restart: unless-stopped
    privileged: true
    command: bash -c "python -u app.py"
