---
version: "2.3"
services:
  video-processor:
    image: kannie/video-processor
    container_name: video-processor
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:/usr/src/app
    environment:
      - KAFKA_CONSUMER_TOPIC=test
      - KAFKA_PRODUCER_TOPIC=meta_test
      - KAFKA_BOOTSTRAP_SERVERS=$DOCKER_HOST_IP:9092
      - KAFKA_CLIENT_ID="processor1"
      - PROCESSOR_URL=$DOCKER_HOST_IP:50051
      - MAX_ASYNC_CALLS=32
    privileged: true
    command: bash -c "python -u app.py"
